export default [
  {
    category: "Perks",
    color: "primary",
    icon: "bag",
    items: [
      {
        name: "Brilliant Premium",
        description: "Free Brilliant Premium student access",
        icon: "code",
        external: false,
        url: "/brilliant.mdx",
        forUseBy: "clubbers",
      },
      {
        name: "Zoom Pro Meetings",
        description: "Run Zoom Pro meetings for free in your Hack Club",
        icon: "welcome",
        external: false,
        url: "/zoom.mdx",
        forUseBy: "clubbers",
      },
      {
        name: "Figma",
        description: "Free access to Figma's team plan",
        icon: "photo",
        external: false,
        url: "/figma.mdx",
        forUseBy: "clubbers",
      },
      {
        name: "Stickers",
        description: "Get a box of stickers for your next meeting or event",
        icon: "sticker",
        external: false,
        url: "/stickers.mdx",
        forUseBy: "leaders",
      },
      {
        name: "Posters",
        description: "Get large Hack Club posters to promote your Hack Club",
        icon: "docs-fill",
        external: true,
        url: "https://forms.hackclub.com/t/uzgyhTqvsFus",
        forUseBy: "leaders",
      },
      {
        name: "Posters - Europe",
        description: "If you're in Europe, get large Hack Club posters to promote your Hack Club",
        icon: "docs-fill",
        external: true,
        url: "https://hack.club/eu-posters",
        forUseBy: "leaders",
      },
      {
        name: "CodeDay",
        description: "Discount for in-person CodeDay events",
        icon: "event-code",
        external: false,
        url: "/codeday.mdx",
        forUseBy: "clubbers",
      },
      {
        name: "Boba Drops",
        description: "Give your club an unfair advantage with free boba",
        icon: "rep",
        external: true,
        url: "https://hack.club/boba",
        forUseBy: "clubbers",
      },
      {
        name: "Hackaccino",
        description: "Get free frappuccinos for your club members",
        icon: "like-fill",
        external: true,
        url: "https://fraps.hackclub.com",
        forUseBy: "clubbers",
      },
      {
        name: "Code Crafters",
        description: "Code crafters free 2 years free membership",
        icon: "code",
        external: true,
        url: "https://codecrafters.io/event/hackclub",
        forUseBy: "clubbers",
      },
      {
        name: "Build Your Own LLM",
        description: "Learn to build and customize your own language model from scratch. Share your work by October 1st to get a free YubiKey and book!",
        icon: "code",
        external: true,
        url: "https://hackclub.slack.com/archives/C01FXNNF6F2/p1725326501200079",
        forUseBy: "clubbers",
      },
      {
        name: "Branding & Logos",
        description: "Make anything Hack Club branded",
        icon: "like",
        external: true,
        url: "https://hackclub.com/brand",
        forUseBy: "everyone",
      },
      {
        name: "DNS",
        description: "Redeem a free hackclub.com subdomain",
        icon: "web",
        external: true,
        url: "https://github.com/hackclub/dns",
        forUseBy: "clubbers",
      },
      {
        name: "Theme Starter",
        description:
          "A sample Next.js project for getting started with MDX, Theme UI, & Hack Club Theme",
        icon: "help",
        external: true,
        url: "https://github.com/hackclub/theme-starter",
        forUseBy: "everyone",
      },
      {
        name: "Theme",
        description: "Hack Club's theme, using Theme UI",
        icon: "grid",
        external: true,
        url: "https://theme.hackclub.com",
        forUseBy: "everyone",
      },
    ],
  },
  {
    category: "Resources",
    color: "blue",
    icon: "explore",
    items: [
      {
        name: "School Toolbox",
        description: "Resources to help with school admin or IT challenges",
        icon: "briefcase",
        external: true,
        url: "https://school-toolbox.hackclub.com",
        forUseBy: "everyone",
      },
      {
        name: "Slack Community",
        description:
          "Be part of a fun, technically-diverse and supportive community on Slack",
        icon: "slack",
        external: true,
        url: "https://hackclub.com/slack",
        forUseBy: "everyone",
      },
      {
        name: "Gas Fund",
        description: "Drive to any high school hackathon and get the cost of gas reimbursed",
        icon: "briefcase",
        external: true,
        url: "https://gas.hackclub.com/",
        forUseBy: "everyone",
      },
      {
        name: "$500 Hackathon Grant",
        description: "Get up to $500 to run an unforgettable hackathon",
        icon: "payment",
        external: true,
        url: "https://hackclub.com/hackathons/grant",
        forUseBy: "clubbers",
      },
      {
        name: "Hackathons Page",
        description:
          "Everything you need to know to run an amazing event, all in one place",
        icon: "event-check",
        external: true,
        url: "https://hackclub.com/hackathons/",
        forUseBy: "everyone",
      },
      {
        name: "HCB",
        description:
          "A full-stack toolkit for organizing anything.",
        icon: "bank-account",
        external: true,
        url: "https://hackclub.com/hcb",
        forUseBy: "everyone",
      },
      {
        name: "Leader Newsletter",
        description: "The bi-weekly run-down for Hack Club leaders",
        icon: "docs",
        external: true,
        url: "https://workshops.hackclub.com/leader-newsletters",
        forUseBy: "leaders",
      }
    ],
  },
  {
    category: "Activities",
    color: "orange",
    icon: "idea",
    items: [
      {
        name: "Workshops",
        description:
          "Learn programming and create fun projects with short, in-depth workshops",
        icon: "idea",
        external: true,
        url: "https://workshops.hackclub.com",
        forUseBy: "everyone",
      },
      {
        name: "AMAs",
        description: "Call someone who we’ve always wanted to talk to—and the entire Hack Club Slack community is invited to ask questions & chat with the guest live.",
        icon: "person",
        external: true,
        url: "https://hackclub.com/amas/",
        forUseBy: "everyone"
      },
      {
        name: "Muse",
        description: "Music programming language",
        icon: "list",
        external: true,
        url: "https://muse.hackclub.com",
        forUseBy: "everyone",
      },
      {
        name: "Events",
        description: "Join an event with other Hack Clubbers",
        icon: "event-code",
        external: true,
        url: "https://events.hackclub.com",
        forUseBy: "clubbers",
      },
      {
        name: "Hackathons",
        description: "Find hackathons to attend",
        icon: "crosshairs",
        external: true,
        url: "https://hackathons.hackclub.com",
        forUseBy: "everyone",
      },
    ],
  },
];
