export default [
  {
    category: "YSWS",
    color: "green",
    icon: "bolt",
    items: [
      {
        name: "Boba Drops",
        description: "Build an HTML + CSS static site, get free boba",
        img: "https://cloud-ktwmd5kff-hack-club-bot.vercel.app/0boba.png",
        background: "#C76B0F",
        titleColor: "#F6D193",
        descriptionColor: "#F6D193",
        external: true,
        url: "https://hack.club/boba",
        fancy: true,
      },
      {
        name: "Hackaccino",
        description: "Make a 3D website, get a free Frappuccino",
        img: "https://cloud-ahkc8uotv-hack-club-bot.vercel.app/0group_15.png",
        background: "#FFF1DE",
        titleColor: "#4F2A0E",
        descriptionColor: "#4F2A0E",
        external: true,
        url: "https://hack.club/fraps",
        fancy: true,
      },
      {
        name: "OnBoard",
        description: "Join 1k teens designing PCBs, learning hardware, and building electronics",
        img: "https://cloud-6skkg6eck-hack-club-bot.vercel.app/0image.png",
        background: "dark",
        titleColor: "green",
        descriptionColor: "white",
        external: true,
        url: "https://hackclub.com/onboard",
        fancy: true,
      },
      {
        name: "Sprig",
        description: "Join hundreds of teenagers making tile-based JavaScript games",
        img: "https://cloud-daf42gs62-hack-club-bot.vercel.app/0sprig.png",
        background: "#000",
        titleColor: "green",
        descriptionColor: "white",
        external: true,
        url: "https://sprig.hackclub.com",
        fancy: true,
      },
      {
        name: "Cider",
        description: "Design, Code, and Ship an iOS app to the App Store in 30 days.",
        img: "https://cloud-m33gqgkp6-hack-club-bot.vercel.app/0image.png",
        background: "#b93c3c",
        titleColor: "#fffffb",
        descriptionColor: "#ffffff",
        external: true,
        url: "https://cider.hackclub.com/",
        fancy: true,
      },
      // Limited-time YSWSs start here
      {
        name: "High Seas",
        description: "Build personal projects. Get free stuff. (Ends January 31)",
        img: "https://cloud-6k139ft24-hack-club-bot.vercel.app/1highseas.png",
        background: "#3eade2",
        titleColor: "#ffffff",
        descriptionColor: "#ffffff",
        external: true,
        url: "https://highseas.hackclub.com/",
        fancy: true,
      },
      {
        name: "Hackapet",
        description: "Code a virtual pet, get a custom Tamagotchi clone (Ends January 31)",
        img: "https://cloud-6k139ft24-hack-club-bot.vercel.app/0hackapet.png",
        background: "#b2daef",
        titleColor: "#137d88",
        descriptionColor: "#137d88",
        external: true,
        url: "https://hackapet.hackclub.dev/",
        fancy: true,
      },
      {
        name: "HackCraft",
        description: "Code a Minecraft mod, get Minecraft (Ends January 31)",
        img: "https://cloud-kgilrkgl7-hack-club-bot.vercel.app/0image.png", // TODO: real logo
        background: "#30AE1F",
        titleColor: "#FFFFFF",
        descriptionColor: "#FFFFFF",
        external: true,
        url: "https://hackcraft.hackclub.com/",
        fancy: true,
      },
      {
        name: "Hacky Holidays",
        description: "Design a PCB holiday decoration and get it printed for free (Ends January 30)",
        img: "https://cloud-6k139ft24-hack-club-bot.vercel.app/2image.png",
        background: "#5abdff",
        titleColor: "#FFFFFF",
        descriptionColor: "#FFFFFF",
        external: true,
        url: "https://hacky-holidays.hackclub.com/",
        fancy: true,
      },
      {
        name: "Say Cheese!",
        description: "Fit a program entirely into a QR code and get a portable printer (Ends January 26)",
        img: "https://cloud-6k139ft24-hack-club-bot.vercel.app/3image.png",
        background: "#FFFFFF",
        titleColor: "#000000",
        descriptionColor: "#000000",
        external: true,
        url: "https://saycheese.hackclub.com/",
        fancy: true,
      },
      {
        name: "RaspAPI",
        description: "Create an API from scratch and get a mini server to host it on (Ends March 10)",
        img: "https://cloud-6k139ft24-hack-club-bot.vercel.app/4raspberrypi.webp",
        background: "#000000",
        titleColor: "#16a34a",
        descriptionColor: "#16a34a",
        external: true,
        url: "https://raspapi.hackclub.com/",
        fancy: true,
      },
    ],
  },
  {
    category: "Activities",
    color: "orange",
    icon: "idea",
    items: [
      {
        name: "Workshops",
        description:
          "Learn programming and create fun projects with short, in-depth workshops",
        icon: "idea",
        external: true,
        url: "https://workshops.hackclub.com",
        forUseBy: "everyone",
      },
      {
        name: "Muse",
        description: "Music programming language",
        icon: "list",
        external: true,
        url: "https://muse.hackclub.com",
        forUseBy: "everyone",
      },
    ],
  },
  {
    category: "Resources",
    color: "blue",
    icon: "explore",
    items: [
      {
        name: "High Seas",
        description: "Turn any coding project into a YSWS",
        icon: "crosshairs",
        external: true,
        url: "https://highseas.hackclub.com/?utm_medium=hc-channel&utm_campaign=clubs&utm_source=clubs",
        forUseBy: "everyone",
      },
      {
        name: "High Seas Pizza Grant",
        description: "$5 for every sign-up to buy food for your club!",
        icon: "crosshairs",
        external: true,
        url: "https://forms.hackclub.com/high-seas-pizza-fund",
        forUseBy: "everyone",
      },
      {
        name: "Pizza Grant",
        description: "$100 to buy food for your club!",
        icon: "briefcase",
        external: true,
        url: "https://hackclub.com/pizza/",
        forUseBy: "everyone",
      },
      {
        name: "Posters",
        description: "Get large Hack Club posters to promote your Hack Club",
        icon: "docs-fill",
        external: true,
        url: "https://forms.hackclub.com/t/uzgyhTqvsFus",
        forUseBy: "leaders",
      },
      {
        name: "International Posters",
        description: "If you're outside of US/Canada, get large Hack Club posters to promote your Hack Club",
        icon: "docs-fill",
        external: true,
        url: "https://hack.club/intl-posters",
        forUseBy: "leaders",
      },
      {
        name: "Branding & Logos",
        description: "Make anything Hack Club branded",
        icon: "like",
        external: true,
        url: "https://hackclub.com/brand",
        forUseBy: "everyone",
      },
      {
        name: "Stickers",
        description: "Get a box of stickers for your next meeting or event",
        icon: "sticker",
        external: false,
        url: "/stickers.mdx",
        forUseBy: "leaders",
      },
      {
        name: "School Toolbox",
        description: "Resources to help with school admin or IT challenges",
        icon: "briefcase",
        external: true,
        url: "https://school-toolbox.hackclub.com",
        forUseBy: "everyone",
      },
      {
        name: "Slack Community",
        description:
          "Be part of a fun, technically-diverse and supportive community on Slack",
        icon: "slack",
        external: true,
        url: "https://hackclub.com/slack",
        forUseBy: "everyone",
      },
      {
        name: "Leadership Guide",
        description: "Advice on how to lead a club",
        icon: "docs-fill",
        external: true,
        url: "https://archived.guide.hackclub.com/#/",
        forUseBy: "leaders",
      },
      {
        name: "Leader Newsletter",
        description: "The bi-weekly run-down for Hack Club leaders",
        icon: "docs",
        external: true,
        url: "https://workshops.hackclub.com/leader-newsletters",
        forUseBy: "leaders",
      },
      {
        name: "DNS",
        description: "Redeem a free hackclub.com subdomain",
        icon: "web",
        external: true,
        url: "https://github.com/hackclub/dns",
        forUseBy: "clubbers",
      },
      {
        name: "Theme Starter",
        description:
          "A sample Next.js project for getting started with MDX, Theme UI, & Hack Club Theme",
        icon: "help",
        external: true,
        url: "https://github.com/hackclub/theme-starter",
        forUseBy: "everyone",
      },
      {
        name: "Theme",
        description: "Hack Club's theme, using Theme UI",
        icon: "grid",
        external: true,
        url: "https://theme.hackclub.com",
        forUseBy: "everyone",
      },
      {
        name: "Gas Fund",
        description: "Drive to any high school hackathon and get the cost of gas reimbursed",
        icon: "briefcase",
        external: true,
        url: "https://gas.hackclub.com/",
        forUseBy: "everyone",
      },
      {
        name: "Hackathons Page",
        description:
          "Everything you need to know to run an amazing event, all in one place",
        icon: "event-check",
        external: true,
        url: "https://hackclub.com/hackathons/",
        forUseBy: "everyone",
      },
      {
        name: "HCB",
        description: "A full-stack toolkit for organizing anything.",
        icon: "bank-account",
        external: true,
        url: "https://hackclub.com/hcb",
        forUseBy: "everyone",
      },
    ],
  },
  {
    category: "Perks",
    color: "primary",
    icon: "bag",
    items: [
      {
        name: "Events",
        description: "Join an event with other Hack Clubbers",
        icon: "event-code",
        external: true,
        url: "https://events.hackclub.com",
        forUseBy: "clubbers",
      },
      {
        name: "AMAs",
        description:
          "Call someone who we’ve always wanted to talk to—and the entire Hack Club Slack community is invited to ask questions & chat with the guest live.",
        icon: "person",
        external: true,
        url: "https://hackclub.com/amas/",
        forUseBy: "everyone",
      },
      {
        name: "Brilliant Premium",
        description: "Free Brilliant Premium student access",
        icon: "code",
        external: false,
        url: "/brilliant.mdx",
        forUseBy: "clubbers",
      },
      {
        name: "Zoom Pro Meetings",
        description: "Run Zoom Pro meetings for free in your Hack Club",
        icon: "welcome",
        external: false,
        url: "/zoom.mdx",
        forUseBy: "clubbers",
      },
      {
        name: "Figma",
        description: "Free access to Figma's team plan",
        icon: "photo",
        external: false,
        url: "/figma.mdx",
        forUseBy: "clubbers",
      },
      {
        name: "CodeDay",
        description: "Discount for in-person CodeDay events",
        icon: "event-code",
        external: false,
        url: "/codeday.mdx",
        forUseBy: "clubbers",
      },
      {
        name: "Code Crafters",
        description: "Code crafters free 2 years free membership",
        icon: "code",
        external: true,
        url: "https://codecrafters.io/event/hackclub",
        forUseBy: "clubbers",
      },
      {
        name: "Hackathons",
        description: "Find hackathons to attend",
        icon: "crosshairs",
        external: true,
        url: "https://hackathons.hackclub.com",
        forUseBy: "everyone",
      },
    ],
  },
];
